apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f8y1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/karthik-jk-tenant/my-app/devfile-sample-f8y1@sha256:c72570fa835a7969d9e6ed8f2cb78a8b2966d051e3eaa98873275d15f863c8bb
        name: my-nodejs
        resources: {}
status: {}
